name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform Action (plan, apply, destroy)"
        required: true
        default: "plan"
        type: choice
        options: [plan, apply, destroy]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Download State
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: terraform-state
          path: terraform/

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        working-directory: terraform
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: terraform
        run: terraform apply -input=false tfplan

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        working-directory: terraform
        run: terraform destroy -auto-approve

      - name: Save State
        if: ${{ github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply' }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform/terraform.tfstate
